# Generated by Django 5.0.4 on 2024-05-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salarios",
            name="receibo",
        ),
        migrations.AddField(
            model_name="salarios",
            name="recibo",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
