# Generated by Django 5.0.4 on 2024-05-03 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salarios", "0002_remove_salarios_receibo_salarios_recibo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salarios",
            name="recibo",
        ),
    ]
