# Generated by Django 5.0.2 on 2024-03-24 15:20

import apps.estudantes.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("escolas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "ano_matricula",
                    apps.estudantes.models.AnoField(
                        validators=[
                            apps.estudantes.models.validate_year,
                            apps.estudantes.models.validate_year,
                        ]
                    ),
                ),
                (
                    "ano_saida",
                    apps.estudantes.models.AnoField(
                        blank=True,
                        null=True,
                        validators=[
                            apps.estudantes.models.validate_year,
                            apps.estudantes.models.validate_year,
                        ],
                    ),
                ),
                (
                    "atividade",
                    models.ManyToManyField(blank=True, to="escolas.atividades"),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="escolas.escola"
                    ),
                ),
                ("mensalidade", models.ManyToManyField(to="escolas.mensalidade")),
            ],
        ),
        migrations.CreateModel(
            name="MensalidadeAtividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escolas.atividades",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensalidade Atividade",
                "verbose_name_plural": "Mensalidades Atividades",
            },
        ),
        migrations.CreateModel(
            name="MensalidadePagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.DateField(blank=True, verbose_name="Mês")),
                (
                    "ano",
                    models.IntegerField(blank=True, default=2024, verbose_name="Ano"),
                ),
                ("paga", models.BooleanField(default=False, verbose_name="Paga")),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensalidades",
                        to="estudantes.aluno",
                    ),
                ),
            ],
        ),
    ]
