# Generated by Django 5.0.4 on 2024-08-28 15:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("escolas", "0003_delete_funcionario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano_matricula", models.CharField(max_length=4)),
                ("ano_saida", models.IntegerField(blank=True, null=True)),
                ("contato", models.CharField(blank=True, max_length=20)),
                (
                    "enc_educacao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Encarregado de Educação",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "atividade",
                    models.ManyToManyField(blank=True, to="escolas.atividades"),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="escolas.escola"
                    ),
                ),
                ("mensalidade", models.ManyToManyField(to="escolas.mensalidade")),
            ],
        ),
        migrations.CreateModel(
            name="MensalidadeAtividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escolas.atividades",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensalidade Atividade",
                "verbose_name_plural": "Mensalidades Atividades",
            },
        ),
        migrations.CreateModel(
            name="MensalidadePagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.CharField(max_length=20, verbose_name="Mês")),
                ("ano", models.IntegerField(verbose_name="Ano")),
                ("paga", models.BooleanField(default=False, verbose_name="Paga")),
                ("atraso", models.BooleanField(default=False)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensalidades",
                        to="estudantes.aluno",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escolas.escola"
                    ),
                ),
            ],
        ),
    ]
