# Generated by Django 5.0.4 on 2024-08-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudantes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="atraso",
            field=models.BooleanField(default=False),
        ),
    ]
