# Generated by Django 5.0.2 on 2024-03-24 16:12

import apps.estudantes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudantes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="ano_matricula",
            field=apps.estudantes.models.AnoField(
                validators=[
                    apps.estudantes.models.validate_year,
                    apps.estudantes.models.validate_year,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="ano_saida",
            field=apps.estudantes.models.AnoField(
                blank=True,
                null=True,
                validators=[
                    apps.estudantes.models.validate_year,
                    apps.estudantes.models.validate_year,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mensalidadepagamento",
            name="ano",
            field=models.DateField(verbose_name="Ano"),
        ),
        migrations.AlterField(
            model_name="mensalidadepagamento",
            name="mes",
            field=models.DateField(verbose_name="Mês"),
        ),
    ]
