# Generated by Django 5.0.2 on 2024-03-26 12:27

import apps.estudantes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudantes", "0006_alter_aluno_ano_matricula_alter_aluno_ano_saida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="ano_matricula",
            field=apps.estudantes.models.AnoField(
                validators=[
                    apps.estudantes.models.validate_year,
                    apps.estudantes.models.validate_year,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="ano_saida",
            field=apps.estudantes.models.AnoField(
                blank=True,
                null=True,
                validators=[
                    apps.estudantes.models.validate_year,
                    apps.estudantes.models.validate_year,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mensalidadepagamento",
            name="mes",
            field=models.CharField(max_length=20, verbose_name="Mês"),
        ),
    ]
