# Generated by Django 5.0.2 on 2024-04-15 14:25

import apps.estudantes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolas", "0002_alter_atividades_options"),
        ("estudantes", "0025_alter_aluno_ano_matricula_alter_aluno_ano_saida"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensalidadepagamento",
            name="escola",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="escolas.escola",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aluno",
            name="ano_matricula",
            field=apps.estudantes.models.AnoField(
                validators=[
                    apps.estudantes.models.validate_year,
                    apps.estudantes.models.validate_year,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="ano_saida",
            field=apps.estudantes.models.AnoField(
                blank=True,
                null=True,
                validators=[
                    apps.estudantes.models.validate_year,
                    apps.estudantes.models.validate_year,
                ],
            ),
        ),
    ]
