# Generated by Django 5.0.2 on 2024-04-22 14:57

import apps.estudantes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudantes", "0032_rename_contacto_aluno_contato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensalidadepagamento",
            name="atraso",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="ano_matricula",
            field=apps.estudantes.models.AnoField(
                validators=[
                    apps.estudantes.models.validate_year,
                    apps.estudantes.models.validate_year,
                ]
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="ano_saida",
            field=apps.estudantes.models.AnoField(
                blank=True,
                null=True,
                validators=[
                    apps.estudantes.models.validate_year,
                    apps.estudantes.models.validate_year,
                ],
            ),
        ),
    ]
