# Generated by Django 5.0.4 on 2024-04-29 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0003_remove_funcionario_horas_funcionario_horas_contrato"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escalaoirs",
            name="taxa",
        ),
    ]
