# Generated by Django 5.0.4 on 2024-05-02 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0004_remove_escalaoirs_taxa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="salario",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salario",
            ),
        ),
    ]
