# Generated by Django 5.0.4 on 2024-05-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0005_alter_funcionario_salario"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="duodecimos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="iban",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
