# Generated by Django 5.0.4 on 2024-06-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0006_funcionario_duodecimos_funcionario_iban"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="contrato",
            field=models.FileField(blank=True, upload_to="contratos"),
        ),
    ]
