# Generated by Django 5.0.4 on 2024-06-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0007_funcionario_contrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="Ativo",
            field=models.BooleanField(default=True),
        ),
    ]
