# Generated by Django 5.0.4 on 2024-06-17 21:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0008_funcionario_ativo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionario",
            old_name="Ativo",
            new_name="ativo",
        ),
        migrations.AddField(
            model_name="funcionario",
            name="carta_rescicao",
            field=models.FileField(blank=True, upload_to="contratos/rescisao"),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="data_fim",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Termo Contrato"
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="data_inicio",
            field=models.DateField(blank=True, null=True, verbose_name="Data Início"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="duodecimos",
            field=models.BooleanField(default=False, verbose_name="Duodécimos"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="iban",
            field=models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="irs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="funcionarios.escalaoirs",
                verbose_name="IRS",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="salario",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salário",
            ),
        ),
    ]
