# Generated by Django 5.0.4 on 2024-05-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("funcionarios", "0005_alter_funcionario_salario"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecibosVencimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=100)),
                (
                    "ficheiro",
                    models.FileField(blank=True, upload_to="salarios/recibos"),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funcionarios.funcionario",
                    ),
                ),
            ],
        ),
    ]
