# Generated by Django 5.0.4 on 2024-05-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recibosvencimento",
            name="data",
            field=models.CharField(max_length=50),
        ),
    ]
