# Generated by Django 5.0.2 on 2024-04-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao", "0002_alter_receita_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
