# Generated by Django 5.0.2 on 2024-04-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao", "0004_rename_file_receita_ficheiro_despesas_ficheiro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesas",
            name="ficheiro",
            field=models.FileField(blank=True, upload_to="despesas/"),
        ),
    ]
