# Generated by Django 5.0.2 on 2024-04-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escolas", "0002_alter_atividades_options"),
        ("gestao", "0006_alter_despesas_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiporeceita",
            name="escola",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="escolas.escola",
            ),
            preserve_default=False,
        ),
    ]
