# Generated by Django 5.0.2 on 2024-04-17 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("escolas", "0002_alter_atividades_options"),
        ("gestao", "0007_tiporeceita_escola"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Receita",
            new_name="Entradas",
        ),
    ]
