# Generated by Django 5.0.2 on 2024-04-17 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("escolas", "0002_alter_atividades_options"),
        ("gestao", "0008_rename_receita_entradas"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TipoReceita",
            new_name="TipoEntrada",
        ),
    ]
