# Generated by Django 5.0.2 on 2024-04-17 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestao", "0009_rename_tiporeceita_tipoentrada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entradas",
            name="fatura",
        ),
    ]
