# Generated by Django 5.0.2 on 2024-04-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestao", "0011_tipodespesa_escola"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entradas",
            name="data",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entradas",
            name="ficheiro",
            field=models.FileField(blank=True, upload_to="Entradas/"),
        ),
    ]
