# Generated by Django 5.0.2 on 2024-04-02 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("escolas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atividades",
            options={},
        ),
    ]
