# Generated by Django 5.0.4 on 2024-04-29 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("escolas", "0002_alter_atividades_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Funcionario",
        ),
    ]
